Repository ember-cli-code-coverage/ember-cli-code-coverage, pull requests merged in 2020-05, with the labels that each got.

#251 fix `InvalidStateError` exception
  lib/attach-middleware.js
  lib/templates/test-body-footer.html
Labels: bug

#248 test cases fail with --path option in 1.0.0-beta.8 version
  index.js
Labels: bug

#252 Drop Node 8 and 11 support.
  .travis.yml
  package.json
Labels: breaking

#253 Update release process
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#254 Migrate to more modern linting setup.
  package.json
  tests/acceptance/smoke-test.js
  yarn.lock
Labels: internal

#255 Update dependencies to latest
  package.json
  yarn.lock
Labels: enhancement

#257 Remove unused babel-plugin-transform-async-to-generator package
  package.json
  yarn.lock
Labels: bug

#256 Remove `co` usage
  package.json
  test/integration/in-repo-addon-coverage-test.js
  test/integration/in-repo-engine-coverage-test.js
Labels: internal

#258 Remove RSVP dependency.
  lib/coverage-merge.js
  package.json
  test/integration/app-coverage-test.js
  test/integration/app-coverage-typescript-test.js
  test/integration/in-repo-addon-coverage-test.js
  test/integration/in-repo-engine-coverage-test.js
  yarn.lock
Labels: enhancement

#259 Remove lodash.concat dependency
  index.js
  package.json
  yarn.lock
Labels: enhancement

#260 Ensure coverage build is parallelizable
  index.js
Labels: bug

#261 Replace `extend` package with `Object.assign`
  lib/config.js
  package.json
  yarn.lock
Labels: enhancement

#262 Fix issue with coverage report.
  lib/templates/test-body-footer.html
  test/unit/index-test.js
Labels: bug
